version: '3.8'

services:
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    networks:
      - verve_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis #options: host.docker.internal, redis, localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - verve_network

networks:
  verve_network:
    driver: bridge
 
